<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.7.6 setup script
 * Date: Thu, 21 Dec 2017 21:07:18 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 't_59;XU&_ejJ';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'JZNa=::)ksdp;.Nky$^F5M1x,CW5{{!p';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>